AllCops:
  Exclude:
    - 'spec/**/*'
    - 'lib/pidfile.rb'
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 100
  AutoCorrect: true

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20
